### PR TITLE
Updated and extended docs for upcoming 1.1 release with Python 3 support

### PR DESCRIPTION
**Pull request by holgerd77**
Hi @kmike, ok, I started from scratch :-), this is a good occasion for me to learn rebasing/squashing a bit better. I know just committed the doc changes, removed the release date in the changelog and leave everything else up to you.

Cheers
Holger

### CODE REVIEW

**Comment by kmike** [comment]
Awesome, thanks @holgerd77! Sorry for being so pickly :)

**Comment by redapple** [comment]
@kmike , so we're ready for 1.1 release?

**Comment by kmike** [comment]
@redapple yes

**Comment by holgerd77** [comment]
? :-)

**Comment by holgerd77** [comment]
Hi @kmike, any chance of a short release of this? I am actually re-checking more or less every day for weeks now :-), I would like to release a new version of my own library, and this dependency is holding me back. Should be just a new tag and a PyPI upload, shouldn't it? Or do you want to wait for the final `Python 3` compatible `Scrapy` release?

Cheers
Holger

**Comment by holgerd77** [comment]
Ok, just a humble reminder every 2+ weeks, hope, that's not too intrusive! :-)

**Comment by redapple** [comment]
@holgerd77 , [scrapy-djangoitem 1.1.0 is now on PyPI](https://pypi.python.org/pypi/scrapy-djangoitem)
PyPI doesn't render the README.rst very well. I don't know what's the reason.

**Pull request merged**
