### PR TITLE
Adds Installing Info to Readme

### PR DESCRIPTION
**Pull request by surfer190**
Added this step so that it is clear how users new to python can quickly use the package

### CODE REVIEW

**Comment by cdvv7788** [comment]
I tried the command, but it didn't work. I think it should be scrapy-djangoitem instead of scrapy-django-item.

**Comment by surfer190** [comment]
Sigh please sort it out...

**Comment by Digenis** [comment]
https://github.com/scrapy-plugins/scrapy-djangoitem/blob/b103ed758e142f087ef3ec6a4aeb2ccd4fa8c566/setup.py#L5

**Comment by redapple** [comment]
This has been fixed in 1.1 release. See https://github.com/scrapy-plugins/scrapy-djangoitem#installation

**Pull request closed without merging**
